### ISSUE TITLE
CloudQuery website

### ISSUE THREAD

**Issue by hermanschaaf** [justmiles/cq-source-crowdstrike#1]
Hi @justmiles, I just stumbled upon this repo while looking for another CloudQuery plugin, it looks great! I'm one of the CloudQuery developers and was wondering if you'd like to list this on the CloudQuery website as a community plugin? Both [here](https://www.cloudquery.io/docs/plugins/sources/overview) (under Community Plugins) and under [integrations](https://www.cloudquery.io/integrations). We've [had requests](https://github.com/cloudquery/cloudquery/issues/9133) for a CrowdStrike plugin before so I'm sure the community would be interested if you think this is ready to be shared more widely :)

**Comment by justmiles** [comment]
Hey @hermanschaaf, thanks for reaching out. Yes, would be happy to see this listed as a community plugin! I've only added the tables that fit my needs so far but certainly happy to add more as the community sees fit.

**Comment by hermanschaaf** [comment]
Great! We've now added a link to this repo from the CloudQuery website :)
