### ISSUE TITLE
Primary Key Error when using with BigQuery

### ISSUE THREAD

**Issue by rushvanth** [justmiles/cq-source-crowdstrike#5]
When using this source plugin with the destination as BigQuery, I am getting the following error: -
```
Error: failed to sync v2 source crowdstrike: rpc error: code = Internal desc = failed to write: failed to flush: primary keys are not supported by the BigQuery plugin (if you are trying to use it as a state backend, this is not currently supported)
2023-08-04T12:42:35Z ERR exiting with error error="failed to sync v2 source crowdstrike: rpc error: code = Internal desc = failed to write: failed to flush: primary keys are not supported by the BigQuery plugin (if you are trying to use it as a state backend, this is not currently supported)" module=cli
```

I see that this error is from this check in the BigQuery plugin for primary keys - https://github.com/cloudquery/cloudquery/blob/main/plugins/destination/bigquery/client/migrate.go#L27

Does this mean the tables for BigQuery should not have any primary keys in them? I tested this by creating a fork and removing the primary key transform from this line - https://github.com/justmiles/cq-source-crowdstrike/blob/main/resources/vulnerabilities.go#L20

But I am still running into the same error. Any help would be appreciated.

Thanks!

**Comment by justmiles** [comment]
Hi @rushvanth, I don't have experience with BigQuery and can't talk too intelligently about it, but from what I've read it does not support primary keys. This makes me wonder how the [AWS plugin can sync to BigQuery](https://www.cloudquery.io/integrations/aws/bigquery) as it certainly has primary keys.

I'll do some more research here and see what I can figure out.

**Comment by rushvanth** [comment]
Hey @justmiles,  thanks for the response! Any help would of course be appreciated :)

**Comment by erezrokah** [comment]
Hi 👋 Commented on Discord [too](https://discord.com/channels/872925471417962546/1141003179484528710/1141008026132811796).

BigQuery only supports `write_mode: append` so a configuration should look like:

```yaml
kind: destination
spec:
  name: bigquery
  path: cloudquery/bigquery
  version: "v3.2.1"
  write_mode: "append"
```

That should ensure any PKs are removed from the schema

**Comment by Adequnl3** [comment]
Hi all,

The "write_mode:append" is in the official document (https://www.cloudquery.io/integrations/crowdstrike/bigquery) and still doesn't work. 

{2023-08-22T08:04:52Z ERR exiting with error error="failed to sync v2 source crowdstrike: rpc error: code = Internal desc = failed to write: failed to flush: primary keys are not supported by the BigQuery plugin (if you are trying to use it as a state backend, this is not currently supported)" }

Any further insights would be appreciated. Regards,

**Comment by erezrokah** [comment]
Hi @Adequnl3 can you make sure to use the latest versions of CLI and plugins? Can you share your configuration spec and the CLI version you're using?

**Comment by Adequnl3** [comment]
Sure @erezrokah :

<img width="398" alt="Screenshot 2023-08-22 at 16 07 30" src="https://github.com/justmiles/cq-source-crowdstrike/assets/50166329/ef9a9a82-a422-4d5b-82a7-b9c6d4ef8ea7">

**Comment by erezrokah** [comment]
Thanks for sharing, let me take a look. I think we either need to update the `crowdstrike` plugin to the latest SDK or fix this in the CloudQuery CLI.

**Comment by Adequnl3** [comment]
Thank you @erezrokah your input is appreciated

**Comment by erezrokah** [comment]
Should be fixed via https://github.com/cloudquery/cloudquery/pull/13291

**Comment by erezrokah** [comment]
Hi 👋 We released a new version of the CLI with a fix to this issue. See https://github.com/cloudquery/cloudquery/releases/tag/cli-v3.14.2.

Do you mind upgrading and see if that works?

**Comment by Adequnl3** [comment]
@erezrokah thank you for the effort, upgraded the CLI as suggested: 

<img width="218" alt="Screenshot 2023-08-23 at 20 23 49" src="https://github.com/justmiles/cq-source-crowdstrike/assets/50166329/8517290f-83d6-4911-aaf3-0227e211a33d">

But got the error below:

bash-3.2$ cloudquery sync crowdstrike.yaml bigquery.yaml
Loading spec(s) from crowdstrike.yaml, bigquery.yaml
Starting migration for: crowdstrike (v0.0.4) -> [bigquery (v3.3.0)]
Error: failed to sync v2 source crowdstrike: rpc error: code = Internal desc = failed to write: failed to flush: googleapi: Error 400: Invalid dataset ID "xxx.crowdstrike_bigquery_dataset". Dataset IDs must be alphanumeric (plus underscores) and must be at most 1024 characters long., invalid

**Comment by erezrokah** [comment]
Hi @Adequnl3, you should set the dataset ID without the project id so it should be just `crowdstrike_bigquery_dataset`

**Comment by Adequnl3** [comment]
Hi @erezrokah , thank you did as suggested but got this error:

<img width="1445" alt="Screenshot 2023-08-23 at 20 33 57" src="https://github.com/justmiles/cq-source-crowdstrike/assets/50166329/c69954cc-b4ee-469c-8ee2-6017fd0c01d6">

Created a new dataset but the error persists.

**Comment by erezrokah** [comment]
Thanks for reporting @Adequnl3, can you try with `v3.14.3` of the CLI (see https://github.com/cloudquery/cloudquery/pull/13302). I missed something in my previous fix

**Comment by Adequnl3** [comment]
@erezrokah I can confirm that it works now using cloudquery version 3.14.4:

<img width="460" alt="image" src="https://github.com/justmiles/cq-source-crowdstrike/assets/50166329/cf160ac1-1ea5-4a3a-8d56-54aab1531845">

Thank you for your assistance, Best Regards,

**Comment by erezrokah** [comment]
Thanks for confirming @Adequnl3. I think we can close this issue now, WDYT?

**Comment by Adequnl3** [comment]
Yeah I think so, thank you for the dedication to resolve this @erezrokah

**Comment by justmiles** [comment]
Thanks @erezrokah and @Adequnl3
